### ISSUE TITLE
[Feature] 애플리케이션의 버전 정보를 조회하는 API를 작성한다.

### ISSUE THREAD

**Issue by Dltmd202** [boostcampwm2023/iOS02-moti#21]
## issue
현재 애플리케이션에 배포된 최신 버전과, 최소 필요 버전을 조회하는 API를 작성한다.

## todo
- [ ] 버전을 명시하기 위한 데이터베이스를 세팅한다.
- [ ] 버전 조회를 위한 API를 작성한다.

**Comment by Dltmd202** [comment]
일단은 프로토타입 형태로 이런식으로 구성하려하는데 괜찮을까요? @looloolalaa @jeongju9216 

* `latest`: 최신버전
*  `required`: 최소버전

![image](https://github.com/boostcampwm2023/iOS02-moti/assets/75921696/acc2b737-d74a-4088-9695-fc9199fa5fed)

**Comment by jeongju9216** [comment]
버전은 좋습니다!!
개인정보처리방침 페이지 URL을 담을 Privacy Policy URL 키도 하나 추가 부탁드립니다!
타입은 String으로 부탁드리고, 지금은 값을 빈 문자열로 보내주셔도 괜찮아요.

**Comment by Dltmd202** [comment]
아하!  Privacy Policy 알겠습니다.

```json
{
    "latest": "0.5.0",
    "required": "0.3.0",
    "privacyPolicy": "https://motimation.site/privacy/policy"
}
```
나중에 구체적인 API 설계할 때 구체적인 API 스펙은 수정되더라도
일단은 프로토타입 자체는 이런 형태로 응답하는 걸로 개발해 놓겠습니다!

**Comment by jeongju9216** [comment]
감사합니다!!
