### ISSUE TITLE
그룹의 정보를 정보를 조회하기 위한 API를 작성한다.

### ISSUE THREAD

**Issue by Dltmd202** [boostcampwm2023/iOS02-moti#273]
클라이언트에서 저장해놓은걸 그대로 사용하실지도 모르겠네요❓❓❓

**Comment by lsh23** [comment]
해당 API는 말씀하신대로 클라이언트에서 그룹 리스트에서 받은 정보를 계속 가지고 사용하는 것으로 결정되었습니다.
close #270 
close #274 
close #273
